session:
  name: "dev"
  windows:
    - name: "dotfiles"
      root: "~/Developer/Code/nanofiles"
      panes:
        - cmd: "ls"
    - name: "cask"
      root: "~/Developer/Projects/caskroom/"
      layout: even-horizontal
      panes:
        - cmd: "echo 'Chatori?'"
        - cmd: "cd ~/Downloads"
    - name: "NAND2Tetris"
      root: "~/Developer/Projects/nand2tetris"
      panes:
        - cmd: "ls"
